### ISSUE TITLE
New chapters to write

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/rscss#30]
It's probably time to extend this guide with more specific guidelines on scenarios that people want to hear more from.
- [ ] On `@extend` and refactoring them to mixins
- [ ] On structuring your components, layouts, and helper files
- [ ] Avoiding `>` selector overcomplexity (#7)
- [ ] Add notes on using preprocessors (#3)
- [ ] Add guidelines for writing responsive media queries (#27)

**Comment by davidkpiano** [comment]
Hey @rstacruz, just a note - @-extend lends itself very well to the RSCSS architecture: http://www.smashingmagazine.com/2015/05/extending-in-sass-without-mess/ I'm actually giving a presentation at Sass Summit tomorrow on @-extend and am using RSCSS primarily to outline the concepts. Will you be writing on how to avoid @-extend in favor of mixins, or good strategies for @-extend?

**Comment by JacobDB** [comment]
Have you made any progress on this? I'm very interested in how you recommend going about folder organization and media queries in particular. I'd like to use this system in the new design for my blog, but I'm confused on those items. :)

**Comment by exalted** [comment]
:+1:
